apiVersion: v1
kind: Secret
metadata:
  name: stock-game-secrets
  namespace: stock-game
type: Opaque
stringData:
  DATABASE__POSTGRES_USER: "${POSTGRES_USER}"
  DATABASE__POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  SECURITY__JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
  SECURITY__JWT_ALGORITHM: "HS256"
  SECURITY__ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  SECURITY__REFRESH_TOKEN_EXPIRE_MINUTES: "20160"
